### ISSUE TITLE
Add gitbucket-monitoring-plugin

### ISSUE THREAD

**Issue by yoshinorin** [gitbucket-plugins/gitbucket-plugins.github.io#20]
This plugin display machine information, resources, processes, Java information and GitBucket's log.
Could you please add it to community-plugins list ?

https://github.com/YoshinoriN/gitbucket-monitoring-plugin

**Comment by aadrian** [comment]
plug-in added to the list http://gitbucket-plugins.github.io/

If you wish another icon for the plug-in, please chose one of http://fontawesome.io/icons/ (not already used by other plug-ins)

**Comment by yoshinorin** [comment]
@aadrian Thanks !
