### ISSUE TITLE
Add gitbucket-html5media-plugin

### ISSUE THREAD

**Issue by kounoike** [gitbucket-plugins/gitbucket-plugins.github.io#21]
Please add [kounoike/gitbucket-html5media-plugin](https://github.com/kounoike/gitbucket-html5media-plugin).
It renders HTML5 video/audio tag for mp4/mp3/etc file and show PDF by object tag.

**Comment by aadrian** [comment]
Very useful plug-in, but please also describe how to configure GitLFS so that this plug-in works smoothly for everybody with the mentioned media types.

**Comment by kounoike** [comment]
@aadrian  Add it to README.md now.

**Comment by aadrian** [comment]
plug-in added to the list http://gitbucket-plugins.github.io/

If you wish another icon for the plug-in, please chose one of http://fontawesome.io/icons/ (not already used by other plug-ins)
