### ISSUE TITLE
Add gitbucket-ipynb-plugin

### ISSUE THREAD

**Issue by kounoike** [gitbucket-plugins/gitbucket-plugins.github.io#22]
Please add [kounoike/gitbucket-ipynb-plugin](https://github.com/kounoike/gitbucket-ipynb-plugin).
It render `.ipynb` which is IPython notebook file format. It is useful for data scientists, machine learning developers, and other python/julia/R/etc developers.

**Comment by aadrian** [comment]
Very nice, but IMHO the Readme should also describe (or at least link) how to setup and configure iPython (and what versions), so that users that try this for the first time don't blame GitBucket if something is not working.

**Comment by aadrian** [comment]
plug-in added to the list http://gitbucket-plugins.github.io/

If you wish another icon for the plug-in, please chose one of http://fontawesome.io/icons/ (not already used by other plug-ins)
