### ISSUE TITLE
Plugin request | TimeTracker

### ISSUE THREAD

**Issue by hedibf** [gitbucket-plugins/gitbucket-plugins.github.io#23]
Hello, 

Is there any way to set a work time on *issues* ?
With possibility to view time spent by who on *milestones* ?

BR,
Hédi

**Comment by aadrian** [comment]
@hedibf there's no time tracking functionality in GitBucket itself - GitHub doesn't have one either :) .

Also no GitBucket plug-in has been submitted yet by the community providing such functionality :) .

**Comment by hedibf** [comment]
@aadrian thx for this answer. :+1:
