### ISSUE TITLE
Add gitbucket-mirror-plugin

### ISSUE THREAD

**Issue by alexandremenif** [gitbucket-plugins/gitbucket-plugins.github.io#26]
Hello,

I have just release a plugin for Gitbucket to do repository mirroring. 
Could it be possible to add it to the list of community plugins?

https://github.com/alexandremenif/gitbucket-mirror-plugin

**Comment by aadrian** [comment]
@alexandremenif what version of GitBucket is your plug-in compatible with?

See that all plug-ins keep a "compatibility table" https://github.com/gitbucket-plugins/gitbucket-announce-plugin#compatibility

**Comment by alexandremenif** [comment]
The plugin works on the 4.20 and 4.21. I have not tested lower versions.

I have added the compatibility table to the README.

**Comment by takezoe** [comment]
@alexandremenif Added the mirror plugin to the list. Thanks!

**Comment by alexandremenif** [comment]
Thank you very much!

**Comment by aadrian** [comment]
@alexandremenif Thank you for the plug-in.
