### ISSUE TITLE
Project board plugin

### ISSUE THREAD

**Issue by juninho2410** [gitbucket-plugins/gitbucket-plugins.github.io#29]
I would like to suggest a project management plugin, like new project tabs from github, where you could use the gitbucket tool as a project maganement tool, integrated with bug tracking(issues) independent of repositories or linked in a repository. 
It could be simillar to Trello as well. I don't know the best way, but the necessity is project management integrated inside gitbucket tool.

**Comment by aadrian** [comment]
@juninho2410 there's https://github.com/kasancode/gitbucket-label-kanban-plugin now that allows you to have a Kanban Board per project.

**Comment by juninho2410** [comment]
Tks, i'll test it.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
