### ISSUE TITLE
Add gitbucket-application-logs-plugin

### ISSUE THREAD

**Issue by yoshinorin** [gitbucket-plugins/gitbucket-plugins.github.io#31]
This plugin support gitbucket log feature for Administrator.
> https://github.com/YoshinoriN/gitbucket-application-logs-plugin

Could you please add it to community-plugins list ?

All feature are belows.
* Display LogBack configuration
* Reload LogBack configuration
* Download GitBucket log
* GitBucket logs viewer
    * Multiple logs support
    * Selectable Sort type (ascending or descending from tail of the log)
    * Specify the number of display less than 10000

**Comment by McFoggy** [comment]
cool plugin

**Comment by yoshinorin** [comment]
@McFoggy Thanks!
