### ISSUE TITLE
Add gitbucket-plugins : gitbucket-swagger-plugin

### ISSUE THREAD

**Issue by onukura** [gitbucket-plugins/gitbucket-plugins.github.io#36]
This plugin provide rendering feature for Swagger (OpenAPI) files.
Inspired by GitLab feature(https://gitlab.com/gitlab-org/gitlab/-/merge_requests/21106).
Could you please add it to community-plugins list ?
https://github.com/onukura/gitbucket-swagger-plugin

**Comment by takezoe** [comment]
@onukura Thanks for letting us know your plugin! However, https://github.com/onukura/gitbucket-swagger-plugin shows 404. Maybe this one? https://github.com/onukura/gitbcket-swagger-plugin

I think it's better to rename repository :-)

**Comment by onukura** [comment]
Thank you for your response. And Im sorry for my misspell.... I fixed my repo. name!
